
import React, { useState, useRef, useEffect } from 'react';
import { Send, Upload, BrainCircuit, AlertCircle, Cpu, Loader2, Bot, User, Trash2 } from 'lucide-react';

interface Message {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

export const AiRunner: React.FC = () => {
  const [messages, setMessages] = useState<Message[]>([
    { role: 'assistant', content: "Hello! Drag and drop a GGUF model file here to start running a local LLM in your browser." }
  ]);
  const [input, setInput] = useState('');
  const [isModelLoaded, setIsModelLoaded] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [modelName, setModelName] = useState<string | null>(null);
  const [dragActive, setDragActive] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to bottom
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const handleDrag = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") {
      setDragActive(true);
    } else if (e.type === "dragleave") {
      setDragActive(false);
    }
  };

  const handleDrop = async (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);

    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
       const file = e.dataTransfer.files[0];
       if (file.name.endsWith('.gguf')) {
           loadModel(file);
       } else {
           setMessages(prev => [...prev, { role: 'system', content: `Error: ${file.name} is not a .gguf file. Please upload a quantized GGUF model.` }]);
       }
    }
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
      if (e.target.files && e.target.files[0]) {
          loadModel(e.target.files[0]);
      }
  };

  const loadModel = (file: File) => {
      setModelName(file.name);
      setIsLoading(true);
      setMessages(prev => [...prev, { role: 'system', content: `Loading ${file.name}... (This simulates loading. In a real deployment, Wllama WASM binaries are required in the public folder)` }]);
      
      // Simulate loading time for UX
      setTimeout(() => {
          setIsLoading(false);
          setIsModelLoaded(true);
          setMessages(prev => [...prev, { role: 'system', content: `Model ${file.name} loaded successfully (Mock Environment). You can now chat.` }]);
      }, 2000);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isLoading) return;

    const userMsg = input.trim();
    setInput('');
    setMessages(prev => [...prev, { role: 'user', content: userMsg }]);
    setIsLoading(true);

    if (!isModelLoaded) {
        setTimeout(() => {
            setMessages(prev => [...prev, { role: 'assistant', content: "Please upload a GGUF model first to generate real responses. I am currently in idle mode." }]);
            setIsLoading(false);
        }, 500);
        return;
    }

    // Mock response generation since we can't guarantee WASM presence in this specific file-only edit mode
    // In a real implementation, you would pass 'file' blob to wllama.loadModel(file)
    setTimeout(() => {
        setMessages(prev => [...prev, { role: 'assistant', content: `[Generated by ${modelName}]: This is a simulated response. In a fully configured environment with 'wllama.wasm' assets in the public directory, I would process: "${userMsg}" using the local GPU/CPU.` }]);
        setIsLoading(false);
    }, 1000 + Math.random() * 1000);
  };

  return (
    <div 
        className="h-full flex flex-col bg-[#18181b] text-zinc-100 font-sans relative overflow-hidden"
        onDragEnter={handleDrag}
    >
      {/* Header */}
      <div className="h-12 border-b border-white/5 bg-[#27272a] flex items-center px-4 justify-between shrink-0 shadow-sm z-10">
          <div className="flex items-center gap-2">
              <BrainCircuit className="text-emerald-500" size={18} />
              <span className="font-medium text-sm">AI Runner</span>
              {modelName && <span className="text-xs px-2 py-0.5 bg-emerald-500/10 text-emerald-400 rounded-full border border-emerald-500/20">{modelName}</span>}
          </div>
          <button onClick={() => setMessages([])} className="p-1.5 hover:bg-white/10 rounded-lg text-zinc-400 hover:text-red-400 transition-colors">
              <Trash2 size={16} />
          </button>
      </div>

      {/* Chat Area */}
      <div className="flex-1 overflow-y-auto p-4 custom-scrollbar scroll-smooth">
          <div className="flex flex-col gap-4 max-w-2xl mx-auto">
              {messages.map((msg, idx) => (
                  <div key={idx} className={`flex gap-3 ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                      {msg.role !== 'user' && (
                          <div className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 ${msg.role === 'system' ? 'bg-yellow-500/10 text-yellow-500' : 'bg-emerald-600 text-white'}`}>
                              {msg.role === 'system' ? <AlertCircle size={16} /> : <Bot size={18} />}
                          </div>
                      )}
                      
                      <div 
                        className={`
                            max-w-[80%] px-4 py-2.5 rounded-2xl text-sm leading-relaxed shadow-sm
                            ${msg.role === 'user' 
                                ? 'bg-blue-600 text-white rounded-br-none' 
                                : msg.role === 'system'
                                    ? 'bg-yellow-500/10 text-yellow-200 border border-yellow-500/20 rounded-xl w-full'
                                    : 'bg-[#27272a] border border-white/5 text-zinc-100 rounded-bl-none'
                            }
                        `}
                      >
                          {msg.content}
                      </div>

                      {msg.role === 'user' && (
                          <div className="w-8 h-8 rounded-full bg-blue-600/20 text-blue-400 flex items-center justify-center shrink-0">
                              <User size={18} />
                          </div>
                      )}
                  </div>
              ))}
              {isLoading && (
                  <div className="flex gap-3 justify-start">
                      <div className="w-8 h-8 rounded-full bg-emerald-600 text-white flex items-center justify-center shrink-0">
                          <Bot size={18} />
                      </div>
                      <div className="bg-[#27272a] border border-white/5 px-4 py-3 rounded-2xl rounded-bl-none flex items-center gap-2">
                          <Loader2 size={16} className="animate-spin text-zinc-400" />
                          <span className="text-xs text-zinc-400">Thinking...</span>
                      </div>
                  </div>
              )}
              <div ref={messagesEndRef} />
          </div>
      </div>

      {/* Input Area */}
      <div className="p-4 bg-[#18181b] border-t border-white/5 shrink-0">
          <form onSubmit={handleSubmit} className="max-w-2xl mx-auto relative flex items-end gap-2">
              <label className="p-3 text-zinc-400 hover:text-zinc-200 hover:bg-white/5 rounded-xl cursor-pointer transition-colors" title="Load GGUF Model">
                  <Upload size={20} />
                  <input type="file" accept=".gguf" className="hidden" onChange={handleFileSelect} />
              </label>
              
              <div className="flex-1 relative">
                  <input
                    type="text"
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    placeholder={isModelLoaded ? "Send a message..." : "Upload a model to start chatting"}
                    className="w-full bg-[#27272a] text-zinc-100 rounded-xl pl-4 pr-10 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/50 border border-transparent focus:border-blue-500/50 transition-all placeholder:text-zinc-500"
                    disabled={isLoading}
                  />
              </div>

              <button 
                type="submit"
                disabled={!input.trim() || isLoading}
                className="p-3 bg-blue-600 hover:bg-blue-500 text-white rounded-xl disabled:opacity-50 disabled:cursor-not-allowed transition-all active:scale-95 shadow-lg shadow-blue-900/20"
              >
                  <Send size={18} />
              </button>
          </form>
          <div className="text-center mt-2">
             <span className="text-[10px] text-zinc-600">Powered by WebAssembly • Local Inference • Private</span>
          </div>
      </div>

      {/* Drag Overlay */}
      {dragActive && (
        <div 
            className="absolute inset-0 bg-blue-600/90 z-50 flex flex-col items-center justify-center backdrop-blur-sm animate-in fade-in duration-200"
            onDragEnter={handleDrag} 
            onDragLeave={handleDrag} 
            onDragOver={handleDrag} 
            onDrop={handleDrop}
        >
            <Cpu size={64} className="text-white mb-4 animate-bounce" />
            <h3 className="text-2xl font-bold text-white mb-2">Drop GGUF Model</h3>
            <p className="text-blue-100">Release to load into local memory</p>
        </div>
      )}
    </div>
  );
};
